### PR TITLE
Update `IntroToDSP.ipynb` tutorial to work with `pygama` 1.1.0

### PR DESCRIPTION
**Pull request by slwatkins**
I've updated @iguinn's `IntroToDSP.ipynb` tutorial to work with the current refactored version of `pygama` and added it to the notebooks folder in the sphinx documentation. I've built the docs on my local, and everything works well.

Most of the text is the same as Ian's version --- I updated the JSON config, the various `WaveformBrowser` kwargs being called, use the [legend-testdata-py](https://github.com/legend-exp/legend-testdata-py) package, and added the fix to the current calculation that's mentioned in #316 so the processors are plotted on the correct timescale.

Let me know if there's anything I should add to it!

I should note this is related to Issue #307.

----

Before submitting a pull request, please make sure you've read and understood the pygama developer's guide: https://pygama.readthedocs.io/en/latest/developer.html. In particular, do not forget to:

- [x] Conform to our **coding conventions**
- [x] Update existing or add new **tests**
- [x] Update existing or add new **documentation**
- [x] Address any issue reported by GitHub checks

### CODE REVIEW

**Comment by gipert** [comment]
Thanks Sam for the work! Here are some suggestions from my side:
* remove "Originally written by [...]"
* remove `prereqs` from JSON DSP config
* set `plt.rcParams["figure.figsize"] = (14, 4); plt.rcParams["figure.facecolor"] = "white"; plt.rcParams["font.size"] = 12` like in the `WaveformBrowser` tutorial: https://github.com/legend-exp/pygama/blob/main/docs/source/notebooks/WaveformBrowser.ipynb
* use `us` units in `WaveformBrowser`'s `x_lim` argument
* I would remove the conclusions, they don't fit pygama's manual imo
* Maybe we want to conclude the tutorial by running `build_dsp()` on the test file and show the ouput file contents?
* Try to use more markdown markup where possible, will look nicer on the website!

**Comment by slwatkins** [comment]
@gipert Thanks for the feedback! I've updated the tutorial with your suggestions, and added a bit at the end on using `build_dsp`. I also advertise the other tutorials that exist for more info, so that we don't have the same info in multiple spots.

**Comment by gipert** [comment]
Thanks a lot! I just pushed some minor changes. One last thing: am I wrong or the last cell is supposed to print nicely on the dark theme only? If yes, I would just put
```py
load_dfs('./example_dsp_file.lh5', obj.keys(), 'geds/dsp')
```
in that cell.

**Comment by gipert** [comment]
Can you also remove the old notebook in `tutorials/`?

FYI Black will run on Jupyter notebooks too, once #387 is merged

**Comment by slwatkins** [comment]
@gipert Just removed the old tutorial!

For the styling I added - I saw that when I compiled the docs on my local, it was not very readable (default was dark grey text on a black background) on the documentation site. I'm assuming it'd be the same for the online doc site - I'm happy to remove those lines, but in that case maybe we should add a default Pandas printing style to the docs?

**Comment by slwatkins** [comment]
Ah, nevermind I misunderstood what you were suggesting -> sounds good I'll just remove the printing of the DataFrame!

**Comment by iguinn** [comment]
For reviewing purposes, what's the best way to see the output of a jupyter notebook? Is there a way to see it after it has been run, like this: https://pygama.readthedocs.io/en/stable/notebooks/LH5Files.html, or do I just want to run it myself?

Also, for the future, we should try to use `git mv` when moving files to preserve the history. I don't think it's a big deal for this one since it didn't have much of a history, but as things move around it's something to keep in mind.

**Comment by gipert** [comment]
@iguinn if you click on "details" to the right of the readthedocs GitHub actions check it should forward you to the resulting HTML pages.

**Comment by gipert** [comment]
@iguinn this PR looks good to me. Feel free to merge when you're done reviewing.

**Pull request merged**
