### PR TITLE
Allow init_args to be optimized over in dsp par grid

### PR DESCRIPTION
**Pull request by SamuelBorden**
Allows a parameter grid to be initialized over init_args (the input parameters or constant values used to initialize a gufunc via a factory function).

### CODE REVIEW

**Comment by wisecg** [comment]
I probably should have merged this before creating the 0.8 tag of master for the analysis workshop, but better late than never ...

Thanks Sam!

**Comment by wisecg** [comment]
Oh, I just realized there are some merge conflicts.  Can you take a look at those please?  @SamuelBorden

**Comment by SamuelBorden** [comment]
Fixed the merge conflicts, it should be ready to go!

**Comment by wisecg** [comment]
Sweet!  Merging now.

**Pull request merged**
