### PR TITLE
New Orca/FlashCam keying convention, fix timestamp issue, draft status decoding

### PR DESCRIPTION
**Pull request by jasondet**

### CODE REVIEW

**Comment by jasondet** [comment]
Looks like the tests are finally passing. @mmatteo and @ggmarshall I'm certain you'll need to make some changes in the processing scripts for this. At the very least the table names all need 7 digits instead of 3.

**Comment by gipert** [comment]
Hi Jason, we should add the new field to the channel map. Can you recommend a short and descriptive name?

**Comment by jasondet** [comment]
@gipert how about "FBI"?

**Comment by gipert** [comment]
What if we use a name that makes it clear that this is the identifier used for channels in raw files? So instead of stating "what it is", we would state "how it is used". What do you think?

**Comment by gipert** [comment]
For example, `rawid`.

**Pull request merged**
