### PR TITLE
`processors.get_multi_local_extrema()`: new advanced search methods (+ unit tests)

### PR DESCRIPTION
**Pull request by patgo25**
Added Features to get_multi_local_extrema processor:

- Choose the search direction:
    -  Left to right
    -  Right to Left
    -  Both directions conservative (find the smallest mutual set of extrema)
    -  Both directions aggressive (find the largest set of unique extrema)
- Set different delta limits for minima and maxima search
- Updated tests

### CODE REVIEW

**Comment by gipert** [comment]
Thanks @patgo25! Can you also add a couple of simple unit tests in tests/dsp/processors/test_get_multi_local_extrema.py to this PR?

**Comment by jasondet** [comment]
A couple of questions:
- can you describe in what sort of situations L->R might give a different result from R->L?
- can you describe in what sort of situations one would want different deltas for minima / maxima?
- have you verified that L->R with one delta reproduces the original behavior?

**Comment by patgo25** [comment]
Added some tests @gipert 

@jasondet, the answer to your question is also tested in the tests. But here are the fast answers:
- for symmetric deltas, the search direction doesn't matter
- for asymmetric deltas, it matters:
```
         2
     1   /\  3
     /\/    \/\
    /  a     b \
___/            \____
```
                                             
delta_min =delta_max  is (a little less than) two lines high.
L -> R = L <- R = L<-c-> R = L<-a->R:  Recognized maxima: [2], recognized minima []

delta_min is (a little less than) one line high, and delta_max  is (a little less than) two lines high.
L -> R:  Recognized maxima: [2,3] , recognized minima [b]
L <- R:  Recognized maxima: [2,1] , recognized minima [a] 
L<-c-> R: Recognized maxima: [2] , recognized minima []
L<-a-> R: Recognized maxima: [1,2,3] , recognized minima [a,b]

sorry for my bad ASCII art. ;)

- Specifically, I write this for the SiPM analysis. But this is a little too hard to express in ASCII art ;) we can talk about it somewhere where I can send you actual plots :)
- Generally, you could achieve the thing in the ASCII "plot" above with a smaller symmetric delta. But let's say you have something like this:
```
          2
          /\      4
     1  /   \ 3  /\
     /\/     \/\/  \
    /  a     b  c   \
___/                 \____
```
With a small symm. delta (one line high), you would identify all minima and all maxima.
With an asym delta d_max = 2 lines, d_min = 1 line height, you would get:
L -> R:  Recognized maxima: [2,4] , recognized minima [b]
L <- R:  Recognized maxima: [2,1] , recognized minima [a] 
L<-c-> R: Recognized maxima: [2] , recognized minima []
L<-a-> R: Recognized maxima: [1,2,4] , recognized minima [a,b]
This way, one would mitigate the extrema detection of [c,3]

- L->R with symm. delta reproduces original behavior.

**Comment by jasondet** [comment]
Very nice! And the ascii art was very impressive: effective and helpful! 

I'm all for this. It would be good to have someone more expert like @iguinn or @SamuelBorden or @ggmarshall take a quick look. If any of them gives the thumbs up I'll merge.

**Comment by gipert** [comment]
I reviewed the changes with @patgo25 and they look OK to me. I'll merge if tests pass.

**Comment by gipert** [comment]
We keep getting the Codecov error, that's a known issue but we cannot do anything about that.

**Pull request merged**
