### PR TITLE
New moving linear fit processor for ppc a/e

### PR DESCRIPTION
**Pull request by ggmarshall**
Added a moving linear fit processor that can be used for the ppc a/e. Seems to give better results in testing.

### CODE REVIEW

**Comment by gipert** [comment]
Since https://github.com/legend-exp/pygama/pull/500 is ready for merge I would propose to redirect this PR to https://github.com/legend-exp/dspeed

**Comment by ggmarshall** [comment]
How long is that likely to take? I'd quite like to run a production with this in the next few days?

**Comment by gipert** [comment]
I was just waiting for a final green light from @jasondet, we can merge it today

**Comment by jasondet** [comment]
sorry I didn't see this last week. We just merged 500. Can this be moved to dspeed?

**Pull request closed without merging**
