### PR TITLE
Enable GitHub actions, deploy docs to GitHub pages

### PR DESCRIPTION
**Pull request by gipert**
Hi! I started working on the CI environment for pygama, here's is my to-do list:

- [x] Configure GitHub actions to test the package with different Python versions
- [ ] Actually run test scripts, [here](https://github.com/gipert/pygama/blob/master/.github/workflows/main.yml#L31-L33)
- [x] Configure action to build and deploy Sphinx docs (master branch)
- [x] Add testing in LEGEND container
- [ ] Fix docstring bugs
- [ ] Archive (stable) documentation for tagged pygama versions, keep auto-updating (unstable) documentation for `master`. Maybe easier with https://readthedocs.io?
- [ ] Tune Sphinx settings

You can view the build status (https://github.com/gipert/pygama/actions) and the deployed docs (https://gipert.github.io/pygama) in my fork. As soon as this PR will be merged, GitHub actions will start automatically and the docs will appear at https://legend-exp.github.io/pygama. These are the only actions required to the admins (@wisecg) **before merging this PR**:
- create a `gh-pages` branch in the remote repo (so, locally: `git branch gh-pages && git push origin gh-pages`)
- enable GitHub pages in the repo settings, set it like this:

image

As you'll see later, the `gh-pages` branch will be entirely dedicated to the HTML source and will be kept up to date by the GitHub bots.

Discussion items:
- Which Python versions we want pygama to be compatible with? At the moment, Python 2 builds fail (llvmlite)
- Do we want to restrict the CI builds to the master branch (and PRs)?
- Do we want to automatically run `sphinx-apidoc`? I would say no, because at a certain point we'll start to write custom stuff in the `.rst` files – and we don't want `sphinx-apidoc` to overwrite that
- There are many Sphinx warnings and errors at the moment: https://github.com/gipert/pygama/runs/2067785403?check_suite_focus=true#step:4:191
- I would put all documentation on the docs webpage (possibly in the pygama source code), remove it elsewhere (e.g. `pygama/README.md`)
- I deleted `hdf5_spec.md` because it's a copy of this: http://legend-exp.org/legend-data-format-specs/dev , right?
- Other requests? Stuff that I missed @wisecg?

### CODE REVIEW

**Comment by gipert** [comment]
We could consider moving to https://readthedocs.org to easily store multiple documentation versions

**Comment by wisecg** [comment]
Hey Luigi, thanks for taking a look at this.  The docs on your github page look great!

Just a quick comment -- we should probably not generate documentation for the pygama/experiments or pygama/sandbox folders -- they may be removed in the near future.   Maybe we can remove them before I merge this?

Can I request you paste your discussion items into a slide for Thursday's analysis call?

**Comment by gipert** [comment]
> Just a quick comment -- we should probably not generate documentation for the pygama/experiments or pygama/sandbox folders -- they may be removed in the near future. Maybe we can remove them before I merge this?

Last commit should do the trick, try checking the website again when the GitHub action is done

> Can I request you paste your discussion items into a slide for Thursday's analysis call?

Sure!

**Comment by wisecg** [comment]
Ok Luigi, I made the gh-pages branch.  I'm going to go ahead and try to merge this.

**Comment by gipert** [comment]
https://legend-exp.org/pygama – cool! Just couple of closing remarks @wisecg:

You should remove unsupported Python versions in `.github/workflows/main.yml`, otherwise you'll get emails at every push event, since tests will fail all the time...

I would also move the documentation currently in `pygama/README.md` and in the Wiki on the website. It's a good practice to avoid duplication and try to store docs directly in the source code, if possible, and in the `.rst` files otherwise. In the README I would just keep an essential project description and links to docs and other important resources.

**Pull request merged**
