### PR TITLE
Add ORRunDecoderForRun to Orca decoders

### PR DESCRIPTION
**Pull request by slwatkins**
I wrote up an initial version of the ORRunDecoderForRun, where the data format was taken from http://orca.physics.unc.edu/orca/Data_Chain/Run_Control.html. I've tested it with build_raw on the L200 test data, and it appears to fit well into the workflow (no errors, and the data shows as expected in the outputted LH5 file).

I started this as a draft PR, since I'm not totally clear how exactly we want to write up new decoders and have them fit into pygama.

A couple of quick comments on basic things I was thinking about when writing up this simple decoder:

- Did I put it in the right spot? (i.e. should it live in orca_flashcam.py, or somewhere else?)
- Is the structure okay? I just based the structure on the ORFlashCamListenerConfigDecoder, since they seemed to both be relatively simple decoders
- I arbitrarily named various decoded values, are there specific conventions that I should follow?

I need to add docstrings, and I'm guessing I should add a test as well (or is there a test I should update?).

---------
Before submitting a pull request, please make sure you've read and understood the pygama developer's guide: https://pygama.readthedocs.io/en/latest/developer.html. In particular, do not forget to:

- [x] Conform to our **coding conventions**
- [x] Update existing or add new **tests**
- [x] Update existing or add new **documentation**
- [x] Address any issue reported by GitHub checks

### CODE REVIEW

**Comment by jasondet** [comment]
Nice @slwatkins!

The run records are not specific to FC, it's a general thing for all of Orca. So this decoder should go in its own file, like orca_run_decoder.py

Other than that, it looks good! did you test it?

**Comment by slwatkins** [comment]
@jasondet I just moved over the code to a new file, and added some simple docstrings for documentation.

I've been testing on the LEGEND test data file, and it seems to fit into the workflow well. After running `build_raw` on the L200 test file, things seem to be stored as I'd expect after running `show`:

<details>
  <summary>Output from show</summary>

```python
>>> show('./L200-comm-20220519-phy-geds_test.lh5')

/
├── ORFlashCamADCWaveform · table{packet_id,eventnumber,timestamp,runtime,numtraces,tracelist,baseline,daqenergy,channel,ts_pps,ts_ticks,ts_maxticks,to_mu_sec,to_mu_usec,to_master_sec,to_dt_mu_usec,to_abs_mu_usec,to_start_sec,to_start_usec,dr_start_pps,dr_start_ticks,dr_stop_pps,dr_stop_ticks,dr_maxticks,deadtime,waveform,crate,card,ch_orca,fcid}
│   ├── baseline · array<1>{real}
│   ├── card · array<1>{real}
│   ├── ch_orca · array<1>{real}
│   ├── channel · array<1>{real}
│   ├── crate · array<1>{real}
│   ├── daqenergy · array<1>{real}
│   ├── deadtime · array<1>{real}
│   ├── dr_maxticks · array<1>{real}
│   ├── dr_start_pps · array<1>{real}
│   ├── dr_start_ticks · array<1>{real}
│   ├── dr_stop_pps · array<1>{real}
│   ├── dr_stop_ticks · array<1>{real}
│   ├── eventnumber · array<1>{real}
│   ├── fcid · array<1>{real}
│   ├── numtraces · array<1>{real}
│   ├── packet_id · array<1>{real}
│   ├── runtime · array<1>{real}
│   ├── timestamp · array<1>{real}
│   ├── to_abs_mu_usec · array<1>{real}
│   ├── to_dt_mu_usec · array<1>{real}
│   ├── to_master_sec · array<1>{real}
│   ├── to_mu_sec · array<1>{real}
│   ├── to_mu_usec · array<1>{real}
│   ├── to_start_sec · array<1>{real}
│   ├── to_start_usec · array<1>{real}
│   ├── tracelist · array<1>{array<1>{real}}
│   │   ├── cumulative_length · array<1>{real}
│   │   └── flattened_data · array<1>{real}
│   ├── ts_maxticks · array<1>{real}
│   ├── ts_pps · array<1>{real}
│   ├── ts_ticks · array<1>{real}
│   └── waveform · table{t0,dt,values}
│       ├── dt · array<1>{real}
│       ├── t0 · array<1>{real}
│       └── values · array_of_equalsized_arrays<1,1>{real}
├── ORFlashCamListenerConfig · table{readout_id,fcid,telid,nadcs,ntriggers,nsamples,adcbits,sumlength,blprecision,mastercards,triggercards,adccards,gps,ch_boardid,ch_inputnum}
│   ├── adcbits · array<1>{real}
│   ├── adccards · array<1>{real}
│   ├── blprecision · array<1>{real}
│   ├── ch_boardid · array_of_equalsized_arrays<1,1>{real}
│   ├── ch_inputnum · array_of_equalsized_arrays<1,1>{real}
│   ├── fcid · array<1>{real}
│   ├── gps · array<1>{real}
│   ├── mastercards · array<1>{real}
│   ├── nadcs · array<1>{real}
│   ├── nsamples · array<1>{real}
│   ├── ntriggers · array<1>{real}
│   ├── readout_id · array<1>{real}
│   ├── sumlength · array<1>{real}
│   ├── telid · array<1>{real}
│   └── triggercards · array<1>{real}
├── ORRunDecoderForRun · table{subrun_number,runstartorstop,quickstartrun,remotecontrolrun,heartbeatrecord,endsubrunrecord,startsubrunrecord,run_number,time}
│   ├── endsubrunrecord · array<1>{bool}
│   ├── heartbeatrecord · array<1>{bool}
│   ├── quickstartrun · array<1>{bool}
│   ├── remotecontrolrun · array<1>{bool}
│   ├── run_number · array<1>{real}
│   ├── runstartorstop · array<1>{bool}
│   ├── startsubrunrecord · array<1>{bool}
│   ├── subrun_number · array<1>{real}
│   └── time · array<1>{real}
└── OrcaHeader · string
```
</details>

**Comment by gipert** [comment]
Is this ready for review?

**Comment by slwatkins** [comment]
I'd say so! Marking it ready now.

**Review by gipert — APPROVED** [review]

**Comment by gipert** [comment]
Is this packet type present in any of the Orca test files on legend-testdata?

**Comment by slwatkins** [comment]
They were one of the first couple of packets in the L200 commissioning data, here's the Python code below that opens the file and runs `build_raw`:

```python 
import legend_testdata
from pygama.raw import build_raw
from pygama.lgdo import show

LTD = legend_testdata.LegendTestData()
orca_file = LTD.get_path('orca/fc/L200-comm-20220519-phy-geds.orca')

build_raw(
    orca_file,
    in_stream_type='ORCA',
    out_spec='L200-comm-20220519-phy-geds_test.lh5',
    overwrite=True,
)
show('./L200-comm-20220519-phy-geds_test.lh5')
```

So, all the packets in that truncated file have their decoders now. When we add more decoders, we'll have to use a different file for testing/create a new one with more packet types.

**Comment by gipert** [comment]
OK, should we have a test in this PR or should we wait for a better test file to be uploaded to legend-testdata? We'll have to do it anyways for the Orca decoding validation I guess

**Comment by slwatkins** [comment]
I'd be happy to write one up - it looks like there aren't any for the Orca decoders in general. The only one in `tests/raw/orca/` is the below file, which is just a dummy test.

https://github.com/legend-exp/pygama/blob/main/tests/raw/orca/test_orca_packet.py

Maybe @jasondet has an opinion? I'm fine with making one either way.

**Comment by jasondet** [comment]
The existing test data files should definitely include Run packets -- they are always present in Orca files, so one would have had to surgically remove them, which seems unlikely.

Yes @slwatkins please make a basic test. For the other decoders, tests like test_build_raw() do some good testing for us, but more is always better.

**Comment by slwatkins** [comment]
@gipert @jasondet 

Added a test, mimicking the tests for the FC decoders. I also updated in the lh5_store.py the `np.bool` -> `np.bool_`, as I mentioned in https://github.com/legend-exp/pygama/issues/427#issuecomment-1363360437. Let me know if anything else should be changed, otherwise I think this is good to go!

**Review by gipert — APPROVED** [review]

**Review by jasondet — APPROVED** [review]

**Pull request merged**
