### PR TITLE
Added interpolation option to `fixed_time_pickoff()` processor

### PR DESCRIPTION
**Pull request by iguinn**
Note: this pull request is not yet ready to accept, as changes to processing_chain are required to handle string inputs

- Renamed old `fixed_time_pickoff` to `fixed_sample_pickoff`
- `fixed_time_pickoff` now has a character argument to accept an interpolation mode. Options are:
  - 'i': require integer index (same as `fixed_sample_pickoff`)
  - 'n': nearest-neighbor; round to nearest integer index
  - 'l': linear interpolation
  - 'h': cubic hermite spline interpolation (continuous and once-differentiable; requires 4 nearest samples)
  - 's': cubic natural spline interpolation (continuous and twice-differentiable; requires full waveform)

See issue https://github.com/legend-exp/pygama/issues/325 for more discussion

### CODE REVIEW

**Comment by iguinn** [comment]
The needed processing_chain changes for passing strings as numpy arrays of `int8`s have been added, so this pull request is ready now.
Additional changes from recent commits:
1) Added floor (`f`)/ceiling (`c`) interpolation modes
2) Added `interpolating_upsampler` which upsamples and then fills all the values from same set of interpolation modes used in `fixed_time_pickoff`
3) Added `interpolated_time_point_thresh` which seeks threshold crossings in the same way as `time_point_thresh`, but is capable of returning time points between samples, using the same set of interpolation modes as before (the `h` and `s` modes have not been implemented; they also present an interesting complication, since the splines can overshoot the samples and cross the threshold between different pairs of samples than `time_point_thresh`...)

**Review by jasondet — APPROVED** [review]
Looks good to me. We will need to make it clear that applications (like L60 processing) wanting fixed sample pickoffs need to change their dsp.json's

**Comment by jasondet** [comment]
@ggmarshall or @mmatteo let us know if you are ready for us to merge this

**Comment by gipert** [comment]
I don't understand why this flake8 error shows up now, does it make sense to you @jasondet?

**Comment by jasondet** [comment]
It only just now showed up for the first time... it's a reasonable error though...

Let's see if it's still there after merging other PRs...

**Comment by jasondet** [comment]
flake8 error is fixed in https://github.com/legend-exp/pygama/pull/373, will pull it in

**Comment by jasondet** [comment]
I chatted with @mmatteo over slack. He pointed out that if fixed_time_pickoff() with option "i" is equivalent to fixed_sample_pickoff(), then maybe we shouldn't keep the latter. @iguinn what do you think? Since the signature of fixed_time_pickoff() has changed, no one can accidentally get the wrong behavior, so I think it might be okay not to have fixed_sample_pickoff().

**Comment by iguinn** [comment]
One subtle point is that I added type signatures that accept integers instead of floats for `fixed_sample_pickoff`. This actually goes against our normal ethos of treating indices/times always as floats, and would only really matter for using things like `argmax` that pass integers anyway.

I don't have a problem with getting rid of it though.

**Comment by jasondet** [comment]
@iguinn yes I think since the user is forced to insert an `'i'` to get fixed-sample behavior there is no extra safety from the explicit int typing in the gufunc directive. So I think we can remove fixed_sample_pickoff as suggested by @mmatteo after all.

when you do that, can you also fix the test failure? it looks like a numbification issue but I don't understand why it didn't show up before now.

**Comment by iguinn** [comment]
I can't understand why the tests are failing. From the logs it looks like it is calling trying to call the processor without including the interpolation argument, but when I look at the configuration for the test the argument is there; I'm also able to compile the test file from the legend-testdata repo with the dsp config on my own. It's also failing on the sipm dsp test, which doesn't change at all with this PR.

**Comment by jasondet** [comment]
@gipert can you take a look?

**Comment by iguinn** [comment]
Oooooh found the problem. `multi_a_filter` was modified to call `fixed_time_pickoff` in a parallel branch, so once that got merged into this commit it caused problems. Now the tests seem to be passing.

**Comment by gipert** [comment]
hope we'll have per-processor tests at some point to catch these more easily...

**Comment by mmatteo** [comment]
catching up now. Everything sounds good

**Pull request merged**
