### PR TITLE
Added min_max normalization

### PR DESCRIPTION
**Pull request by esleon97**

### CODE REVIEW

**Comment by gipert** [comment]
Ciao @esleon97, could you describe a use case?

**Comment by esleon97** [comment]
Hi @gipert. I use this to preprocess waveforms before feeding them into my machine learning data cleaning model. This processor ensures that the inputs are constrained to the [-1,1] range, which makes the model perform better.

**Comment by esleon97** [comment]
Hi @gipert. The data cleaning model mostly relies on other Python machine learning packages. I am using pygama to preprocess waveforms (perform discrete wavelet transforms and max/min normalization). I added this processor to have the preprocessing stage done in a single framework while taking advantage of pygama's dsp vectorization. However, I could also incorporate this function without using pygama.

**Comment by gipert** [comment]
> I added this processor to have the preprocessing stage done in a single framework while taking advantage of pygama's dsp vectorization.

The vectorization is done by Numba, so having your processor in a separate package does not introduce any performance penalty -- as long as you decorate it with `@guvectorize`.

For the time being, I would recommend to keep it in your package, let's discuss this again once the code is ready to be integrated ;)

**Pull request closed without merging**
