### PR TITLE
Switch to declarative package management

### PR DESCRIPTION
**Pull request by gipert**
I've been mainly following recommendations from here: https://scikit-hep.org/developer/packaging

* packaging instructions are now contained in `pyproject.toml`, `setup.cfg` (and few lines in `setup.py` to be backward-compatible)
* package source has been moved below `src/` as recommended: simplifies packaging by a lot
* the pygama version is now managed by setuptools, which computes a `git-describe`-like version string automatically. I didn't know about this before and I consider it robust enough (requires just a couple of extra configs in `pyproject.toml` and no extra custom logic). We will not need to manually advance the version string anymore.
* export only pygama version string as LH5 object

Still to do:
- [x] update after #255 is merged
- [x] update contributing guide
- [x] update GHA workflow
- [x] add missing optional dependencies (such as pyfcutils)

@jasondet: are you OK with moving the source below `src/`? Do you have any particular development requirement/need?

**To be merged after #255**

### CODE REVIEW

**Comment by gipert** [comment]
I'm done with this PR – let me know what you think @jasondet @iguinn and feel free to merge, if no objections. https://github.com/legend-exp/pyfcutils/pull/2 should be merged too to make fcutils install seamlessly.

**Comment by jasondet** [comment]
oh wow. this looks like a good idea to me. I've requested that @iguinn and @wisecg review it.

**Comment by wisecg** [comment]
Wow!  I'm impressed at the work here.  I support any change that makes pygama more aligned with best practices in ScikitHEP.   Eventually it would be great to publish this package with them.

The only thing I note here is that we would move the "pygama" dir one level down, to "src/pygama".   As long as Luigi feels that's necessary, I'll support his decision.

**Review by wisecg — APPROVED** [review]

**Comment by gipert** [comment]
> Wow! I'm impressed at the work here. I support any change that makes pygama more aligned with best practices in ScikitHEP. Eventually it would be great to publish this package with them.

I guess it would be nice to contact them at some point, yes: https://scikit-hep.org/affiliated. But ultimately it will depend on pygama's ability to be not-so-much LEGEND-specific.

> The only thing I note here is that we would move the "pygama" dir one level down, to "src/pygama". As long as Luigi feels that's necessary, I'll support his decision.

Yes, it's generally highly recommended as most tools assume this structure by default (and therefore no extra configuration is needed): https://scikit-hep.org/developer/pep621#package-structure

**Comment by jasondet** [comment]
ok. I'm going to merge this...

**Pull request merged**
