### PR TITLE
merge chloe's and jason's Ecal improvements

### PR DESCRIPTION
**Pull request by jasondet**

### CODE REVIEW

**Comment by jasondet** [comment]
@mmatteo or @wisecg let me know if you want to review these before I merge them

**Comment by wisecg** [comment]
@jasondet @cransom12 Nice work here.   There are so many changes here that I recommend someone upload an example script which uses the functions in analysis/calibration.py, etc.

**Review by wisecg — COMMENTED** [review]
@jasondet @cransom12 I recommend we add an example script.  There are so many changes & new functions that it's difficult to see what the recommended workflow should be now.

**Review by mmatteo — APPROVED** [review]
I know that @Kermaidy @ggmarshall and @abialexander have tested the new code. They might have received some instructions from Chloe and could provide a working example as suggested by @wisecg

**Comment by Kermaidy** [comment]
@mmatteo 
I've seen this thread and will check with @abialexander what we can provide.

**Comment by jasondet** [comment]
Great thanks guys. In that case, I'll merge this and we'll get the example codes provided ASAP

**Pull request merged**
