### PR TITLE
Fix `VectorOfVectors` read/write and add fancy indexing support

### PR DESCRIPTION
**Pull request by jasondet**

### CODE REVIEW

**Comment by gipert** [comment]
Thanks Jason! I'll quickly test this and merge if it works for me

**Comment by gipert** [comment]
@jasondet seems to happen indeed only on Linux.

As a quick check, I tried to install `numpy==1.22` and `numpy=1.21`. The segfault is still there.

Here is some (unfortunately not so helpful) stacktrace:
```
pytest -v tests/vis/test_waveform_browser.py 
================================================ test session starts =================================================
platform linux -- Python 3.10.7, pytest-7.1.3, pluggy-1.0.0 -- /home/gipert/.virtualenvs/pygama-gyue/bin/python
cachedir: .pytest_cache
rootdir: /home/gipert/sw/src/legend/pygama, configfile: pyproject.toml
plugins: cov-4.0.0
collected 2 items                                                                                                    

tests/vis/test_waveform_browser.py::test_waveform_browser PASSED                                               [ 50%]
tests/vis/test_waveform_browser.py::test_entry_mask Fatal Python error: Aborted

Current thread 0x00007f9fa842a740 (most recent call first):
  File "/home/gipert/sw/src/legend/pygama/src/pygama/lgdo/lh5_store.py", line 376 in read_object
  File "/home/gipert/sw/src/legend/pygama/src/pygama/lgdo/lh5_store.py", line 1256 in read
  File "/home/gipert/sw/src/legend/pygama/src/pygama/vis/waveform_browser.py", line 162 in __init__
  File "/home/gipert/sw/src/legend/pygama/tests/vis/test_waveform_browser.py", line 133 in test_entry_mask
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/python.py", line 1761 in runtest
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/runner.py", line 338 in from_call
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/main.py", line 322 in _main
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/home/gipert/.virtualenvs/pygama-gyue/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/home/gipert/.virtualenvs/pygama-gyue/bin/pytest", line 8 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, h5py._errors, h5py.defs, h5py._objects, h5py.h5, h5py.h5r, h5py.utils, h5py.h5s, h5py.h5ac, h5py.h5p, h5py.h5t, h5py._conv, h5py.h5z, h5py._proxy, h5py.h5a, h5py.h5d, h5py.h5ds, h5py.h5g, h5py.h5i, h5py.h5f, h5py.h5fd, h5py.h5pl, h5py.h5o, h5py.h5l, h5py._selector, yaml._yaml, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, scipy._lib._ccallback_c, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pandas._libs.ops, numexpr.interpreter, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.tslibs.strptime, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, matplotlib._image, fcutils, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg._cythonized_array_utils, scipy.linalg._flinalg, scipy.linalg._solve_toeplitz, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_lapack, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, _cffi_backend, pywt._extensions._dwt, pywt._extensions._cwt, pywt._extensions._pywt, pywt._extensions._swt, scipy._lib._uarray._uarray, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, pyfftw.pyfftw, scipy.fftpack.convolve, matplotlib.backends._tkagg, PIL._imagingtk (total: 131)
zsh: IOT instruction (core dumped)  pytest -v tests/vis/test_waveform_browser.py
```

We can try to dig into it by writing more tests.

@iguinn do you think the `WaveformBrowser` could be somehow related?

**Comment by gipert** [comment]
The thing is giving me headaches. I cannot reproduce the bug by directly calling `LH5Iterator` (see new tests). Still I'm not sure we can blame `WaveformBrowser`. @iguinn can you help me debugging?

**Comment by iguinn** [comment]
The segfault is calling when `LH5Iterator` calls `LH5Store.read_object` for the first time, and is caused by reading in a `VectorOfVectors` (I tested it with and without the `tracelist` field in the test file, which is the only `VectorOfVectors`, and the segfault only happens when I try reading it). `LH5Iterator` constructs a fixed-size buffer to read data into here on line 1183, and then reuses the buffers constructed by this over and over again. This is actually necessary for processing chain, which expects to reuse the same memory buffer, so resizing it after this step is not an option (this has been my sticking point in implementing `VectorOfVectors` for `ProcessingChain`, too).

The solution here is could to be to set the default `flattened_array` in `VectorOfVectors` large enough that it won't have to be resized, but that is very tricky to do since we don't know what "large enough" is.

**Comment by gipert** [comment]
@iguinn I implemented a hack to ignore the `tracelist` VOV in `WaveformBrowser`. Let me know if you have a better temporary solution. Could you open an issue about VOV support in `LH5Iterator`?

@iguinn I have a problem with the `WaveformBrowser` tutorial. I cannot somehow compare waveform populations with two different browsers. Is it a bug or anything wrong I am doing? 

image

**Comment by gipert** [comment]
`field_mask` wasn't actually passed to `LH5Iterator`. Works now!

**Pull request merged**
