### PR TITLE
Fix VoV  dtype errors

### PR DESCRIPTION
**Pull request by gracesong312**

### CODE REVIEW

**Comment by jasondet** [comment]
perfect. thanks Grace!

**Comment by gipert** [comment]
Hi @gracesong312, I just tried to pull your changes but tests are still failing:
```
../../../../.venv/pygama/lib/python3.10/site-packages/pygama/lgdo/table.py:52: in __init__
    self.resize(new_size=size, do_warn=do_warn)
        __class__  = <class 'pygama.lgdo.table.Table'>
        attrs      = {}
        col_dict   = {'dt': [16. 16. 16. 16. 16. 16.]
{'units': 'ns'}, 't0': [0. 0. 0. 0. 0. 0.]
{'units': 'ns'}, 'values': None}
        do_warn    = False
        self       = {'t0': [0. 0. 0. 0. 0. 0.]
{'units': 'ns'}, 'dt': [16. 16. 16. 16. 16. 16.]
{'units': 'ns'}, 'values': None}
        size       = 6
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = {'t0': [0. 0. 0. 0. 0. 0.]
{'units': 'ns'}, 'dt': [16. 16. 16. 16. 16. 16.]
{'units': 'ns'}, 'values': None}, new_size = 6, do_warn = False

    def resize(self, new_size = None, do_warn = False):
        # if new_size = None, use the size from the first field
        for field, obj in self.items():
            if new_size is None: new_size = len(obj)
>           elif len(obj) != new_size:
E           TypeError: object of type 'NoneType' has no len()
```
I suggest you checkout my `tests` branch and run tests there.

**Comment by gipert** [comment]
Merged too fast...

**Comment by jasondet** [comment]
well, that's a different problem ;) it can be in another PR.

**Pull request merged**
