### PR TITLE
Cleaned up distributions and added a sum_dist class

### PR DESCRIPTION
**Pull request by SamuelBorden**
Before submitting a pull request, please make sure you've read and understood the pygama developer's guide: https://pygama.readthedocs.io/en/latest/developer.html. In particular, do not forget to:

- [x] Conform to our **coding conventions**
- [x] Update existing or add new **tests**
- [x] Update existing or add new **documentation**
- [x] Address any issue reported by GitHub checks

### CODE REVIEW

**Comment by jasondet** [comment]
@SamuelBorden I think we need to merge recent main updates into refactor before merging this PR. Okay if I do that or did you want to?

**Comment by SamuelBorden** [comment]
@jasondet It would probably be safer if you did it, I'm still getting used to GitHub

**Comment by gipert** [comment]
Here you go @SamuelBorden ;)

**Comment by CJNave613** [comment]
@jasondet @SamuelBorden Looks like all the checks have passed, are we almost ready to merge this? I'm at a stopping point with energy cal where I might just want to wait for the math refactor to change all my code.

**Comment by gipert** [comment]
Can we merge this?

**Comment by jasondet** [comment]
discussed with @SamuelBorden, this is ready to merge

**Pull request merged**
